---
title: "Plotly test"
author: "Jose Figueroa"
date: 05/17/2020
output: html_notebook
---

Testing plotly [interactive tooltip](https://plotly.com/ggplot2/interactive-tooltip/)


```{r setup, echo=FALSE, include=FALSE}
if(!require("plotly")) {
  install.packages("plotly")
  library(plotly)
}
knitr::opts_knit$set(root.dir = "../")
```


```{r imports, echo=FALSE}
source("modules/Source.R")
source("modules/data_load.R")
source("modules/preprocessing.R")
```

New cases map from deltas.rmd
```{r}
library(zoo)
NY_region_palette.df <- NY_counties_regions %>%
dplyr::select(Region,Color) %>% 
dplyr::distinct(Region,Color)

NY_region_palette <- setNames(as.character(NY_region_palette.df$Color), as.character(NY_region_palette.df$Region))

g <- covid_NY_TS_plot.cases %>%
  group_by(Region, date) %>%
  summarise(diff = sum(diff)) %>%
  mutate(ma = c(NA, NA,rollmean(diff, 3, align = "right"))) %>%
      ggplot(aes(date, 
                 ma, 
                 color = Region)) +
      scale_color_manual(values=NY_region_palette) +
      geom_line(size = 1) +
      scale_y_continuous(
        trans = "log10",
        breaks = c(10,100,500,1000,5000,10000, 50000)
      ) +
      scale_x_datetime(date_breaks = "1 week", date_minor_breaks = "1 day", date_labels = "%b %d") +
      ylab("New Cases") + 
      xlab("Date") +
      ggtitle("New York State NEW reported COVID-19 Cases") +
      geom_vline(aes(xintercept=as_datetime("2020-03-20"), linetype="Gov. Cuomo issues stay-at-home order"), color = "black") + 
      scale_linetype_manual(name = "Events", 
                            values = c(2), 
                            guide = guide_legend(override.aes = list(color = c("black")))) +
      NULL
g
```

Plotly test
```{r}
p <- ggplotly(g)
p
```

