---
title: "NBGWAS"
author: "mouh"
date: "8/12/2020"
output:
  html_document: default
---

# Setup Environment

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "../")

library("MASS")
library("lme4")
library('caret')
library('blmeco')
library(VineCopula)
library(sgof)
library(tidyverse)
library(cvms)
library(pracma)
```

# Set date of analysis

```{r}

sampledata <- readRDS('./Preprocessing_FTS_Outputs/07-06-2020data.Rds')

```

# List of all Interested variables

```{r}

args <- c("% Fair or Poor Health", "Average Number of Physically Unhealthy Days", "% Smokers", "% With Access to Exercise Opportunities", 
          "# Chlamydia Cases", "Chlamydia Rate", "% Uninsured", "# Primary Care Physicians", "# Mental Health Providers", 
          "Mental Health Provider Rate", "Mental Health Provider Ratio", "Preventable Hosp. Rate (White)", "% Screened (White)", 
          "Labor Force", "% Unemployed", "# Households", "Average Daily PM2.5", "Presence of Water Violation", "# Workers who Drive Alone", 
          "% Long Commute - Drives Alone", "% Frequent Physical Distress", "# HIV Cases", "# Food Insecure", "# Limited Access", 
          "# Drug Overdose Deaths", "# Motor Vehicle Deaths", "MV Mortality Rate (White)", "% Insufficient Sleep", "# Uninsured_1", 
          "% Uninsured_1", "# Uninsured_2", "% Uninsured_2", "Other Primary Care Provider Rate", "Average Grade Performance (White)_1", 
          "Segregation index", "# Homeowners", "# Households with Severe Cost Burden", "# less than 18 years of age", 
          "% Not Proficient in English", "All.Cause.death_rate", "infant_deaths", "suicide_deaths", "reclosure", "mask", "date_since_social", 
          "date_since_reopen", "date_since_reclosure", "beds", "date_since_mask", "date_since", "Assault.death_rate", "Cancer.death_rate", 
          "Cardiovascular.death_rate", "Despair.death_rate", "PediatricAsthma", "AdultAsthma", "COPD", "AdultChronicLungDisease")
```

# Loop through all interested variables to perform a complete NBGWAS analysis

```{r}
for (interested_var in args){
  # Filter sampledata to fixed variables and interested variable ready for analysis
  sub_sampledata <- subset(sampledata, select = c ("Deaths","hispanic", "pct_blk", "pct_asian", "pct_white", "pct_native", "q_popdensity",
                                                   "medhouseholdincome", "education", "beds", "population", "date_since", 
                                                   "date_since_mask", "State", interested_var))

  colnames(sub_sampledata)[ncol(sub_sampledata)] = "i_var"
  
  # If interested variable is not numerical, factorize it when put into model or scale it otherwise.
  if (strcmp(unname(sapply(sub_sampledata, typeof)[ncol(sub_sampledata)]), "character")) {
    In.loop.model=glmer.nb(Deaths ~ scale(hispanic) + scale(pct_blk) + scale(pct_asian) + scale(pct_white) + scale(pct_native)
                           + factor(q_popdensity)
                           + scale(log(medhouseholdincome))+scale(education) + scale(beds/population)
                           + scale(date_since) 
                           + scale(date_since_mask)
                           + factor(i_var)
                           + (1|State)
                           + offset(log(population)), data = sub_sampledata)
  } else {
    In.loop.model=glmer.nb(Deaths ~ scale(hispanic) + scale(pct_blk) + scale(pct_asian) + scale(pct_white) + scale(pct_native)
                           + factor(q_popdensity)
                           + scale(log(medhouseholdincome))+scale(education) + scale(beds/population)
                           + scale(date_since) 
                           + scale(date_since_mask)
                           + scale(i_var)
                           + (1|State)
                           + offset(log(population)), data = sub_sampledata)
  }
  
  # 3 Steps of saving results: 
  
  # 1. Read in rds saved from last iteration
  GWAS_MRR <- readRDS("GWAS/GWAS_MRR.rds")
  GWAS_P <- readRDS("GWAS/GWAS_P.rds")
  GWAS_ADJ_P <- readRDS("GWAS/GWAS_ADJ_P.rds")
  
  # 2. Append/Modify values obtained from current iteration to dataframe
  GWAS_MRR[[interested_var]]   <- summary(In.loop.model)[10]$coefficients[2:16,1]
  GWAS_P[[interested_var]]     <- summary(In.loop.model)[10]$coefficients[2:16,4]
  GWAS_ADJ_P[[interested_var]] <- p.adjust(summary(In.loop.model)[10]$coefficients[2:16,4], 
                                           method = 'BH', 
                                           n = length(summary(In.loop.model)[10]$coefficients[2:16,4]))
  
  # 3. Override rds file with updated dataframe
  saveRDS(GWAS_ADJ_P, "GWAS/GWAS_ADJ_P.rds")
  saveRDS(GWAS_P, "GWAS/GWAS_P.rds")
  saveRDS(GWAS_MRR, "GWAS/GWAS_MRR.rds")  
}

```