#!/usr/bin/env bash

declare -a var_names=("fips" "mean_pm25" "mean_winter_temp" "mean_summer_temp" "mean_winter_rm" "mean_summer_rm" "Lat" "Long_" 
"Confirmed" "Deaths" "Recovered" "Active" "Incidence_Rate" "Case.Fatality_Ratio" "poverty" "popdensity" "medianhousevalue" 
"pct_owner_occ" "education" "population" "q_popdensity" "older_pecent" "young_pecent" "prime_pecent" "mid_pecent" "State" "County" 
"Years of Potential Life Lost Rate" "YPLL Rate (AIAN)" "YPLL Rate (Asian)" "YPLL Rate (Black)" "YPLL Rate (Hispanic)" "YPLL Rate (White)" 
"% Fair or Poor Health" "Average Number of Physically Unhealthy Days" "Average Number of Mentally Unhealthy Days" "% Low Birthweight" 
"% LBW (AIAN)" "% LBW (Asian)" "% LBW (Black)" "% LBW (Hispanic)" "% LBW (White)" "% Smokers" "pct_obesity" "Food Environment Index" 
"% Physically Inactive" "% With Access to Exercise Opportunities" "% Excessive Drinking" "# Alcohol-Impaired Driving Deaths" 
"# Driving Deaths" "% Driving Deaths with Alcohol Involvement" "# Chlamydia Cases" "Chlamydia Rate" "Teen Birth Rate" "Teen Birth Rate (AIAN)" 
"Teen Birth Rate (Asian)" "Teen Birth Rate (Black)" "Teen Birth Rate (Hispanic)" "Teen Birth Rate (White)" "# Uninsured" "% Uninsured" 
"# Primary Care Physicians" "Primary Care Physicians Rate" "Primary Care Physicians Ratio" "# Dentists" "Dentist Rate" "Dentist Ratio" 
"# Mental Health Providers" "Mental Health Provider Rate" "Mental Health Provider Ratio" "Preventable Hospitalization Rate" 
"Preventable Hosp. Rate (AIAN)" "Preventable Hosp. Rate (Asian)" "Preventable Hosp. Rate (Black)" "Preventable Hosp. Rate (Hispanic)" 
"Preventable Hosp. Rate (White)" "% With Annual Mammogram" "% Screened (AIAN)" "% Screened (Asian)" "% Screened (Black)" 
"% Screened (Hispanic)" "% Screened (White)" "% Vaccinated" "% Vaccinated (AIAN)" "% Vaccinated (Asian)" "% Vaccinated (Black)" 
"% Vaccinated (Hispanic)" "% Vaccinated (White)" "Cohort Size" "High School Graduation Rate" "# Some College" "% Some College" "# Unemployed" 
"Labor Force" "% Unemployed" "% Children in Poverty" "% Children in Poverty (AIAN)" "% Children in Poverty (Asian)" 
"% Children in Poverty (Black)" "% Children in Poverty (Hispanic)" "% Children in Poverty (White)" "80th Percentile Income" 
"20th Percentile Income" "Income Ratio" "# Single-Parent Households" "# Households" "% Single-Parent Households" "# Associations" 
"Social Association Rate" "Annual Average Violent Crimes" "Violent Crime Rate" "# Injury Deaths" "Injury Death Rate" 
"Injury Death Rate (AIAN)" "Injury Death Rate (Asian)" "Injury Death Rate (Black)" "Injury Death Rate (Hispanic)" 
"Injury Death Rate (White)" "Average Daily PM2.5" "Presence of Water Violation" "% Severe Housing Problems" "Severe Housing Cost Burden" 
"Overcrowding" "Inadequate Facilities" "% Drive Alone to Work" "% Drive Alone (AIAN)" "% Drive Alone (Asian)" "% Drive Alone (Black)" 
"% Drive Alone (Hispanic)" "% Drive Alone (White)" "# Workers who Drive Alone" "% Long Commute - Drives Alone" "Life Expectancy" 
"Life Expectancy (AIAN)" "Life Expectancy (Asian)" "Life Expectancy (Black)" "Life Expectancy (Hispanic)" "Life Expectancy (White)" 
"pre_covid_deaths" "pre_covid_death_rate" "Age-Adjusted Mortality (AIAN)" "Age-Adjusted Mortality (Asian)" "Age-Adjusted Mortality (Black)" 
"Age-Adjusted Mortality (Hispanic)" "Age-Adjusted Mortality (White)" "child_deaths" "Child Mortality Rate" "Child Mortality Rate (AIAN)" 
"Child Mortality Rate (Asian)" "Child Mortality Rate (Black)" "Child Mortality Rate (Hispanic)" "Child Mortality Rate (White)" 
"infant_deaths" "Infant Mortality Rate" "Infant Mortality Rate (AIAN)" "Infant Mortality Rate (Asian)" "Infant Mortality Rate (Black)" 
"Infant Mortality Rate (Hispanic)" "Infant Mortality Rate (White)" "% Frequent Physical Distress" "% Frequent Mental Distress" "pct_diabetes"
"# HIV Cases" "HIV Prevalence Rate" "# Food Insecure" "% Food Insecure" "# Limited Access" "% Limited Access to Healthy Foods" 
"# Drug Overdose Deaths" "Drug Overdose Mortality Rate" "Drug Overdose Mortality Rate (AIAN)" "Drug Overdose Mortality Rate (Asian)" 
"Drug Overdose Mortality Rate (Black)" "Drug Overdose Mortality Rate (Hispanic)" "Drug Overdose Mortality Rate (White)" 
"# Motor Vehicle Deaths" "Motor Vehicle Mortality Rate" "MV Mortality Rate (AIAN)" "MV Mortality Rate (Asian)" "MV Mortality Rate (Black)" 
"MV Mortality Rate (Hispanic)" "MV Mortality Rate (White)" "% Insufficient Sleep" "# Uninsured_1" "% Uninsured_1" "# Uninsured_2" 
"% Uninsured_2" "Other Primary Care Provider Rate" "Other Primary Care Provider Ratio" "% Disconnected Youth" "Average Grade Performance" 
"Average Grade Performance (Asian)" "Average Grade Performance (Black)" "Average Grade Performance (Hispanic)" 
"Average Grade Performance (White)" "Average Grade Performance_1" "Average Grade Performance (Asian)_1" "Average Grade Performance (Black)_1"
"Average Grade Performance (Hispanic)_1" "Average Grade Performance (White)_1" "Median Household Income" "Household Income (AIAN)" 
"Household Income (Asian)" "Household Income (Black)" "Household Income (Hispanic)" "Household Income (White)" 
"% Enrolled in Free or Reduced Lunch" "Segregation index" "Segregation Index" "Homicide Rate" "Homicide Rate (AIAN)" 
"Homicide Rate (Asian)" "Homicide Rate (Black)" "Homicide Rate (Hispanic)" "Homicide Rate (White)" "suicide_deaths" 
"Suicide Rate (Age-Adjusted)" "Crude Rate" "Suicide Rate (AIAN)" "Suicide Rate (Asian)" "Suicide Rate (Black)" "Suicide Rate (Hispanic)" 
"Suicide Rate (White)" "# Firearm Fatalities" "Firearm Fatalities Rate" "Firearm Fatalities Rate (AIAN)" "Firearm Fatalities Rate (Asian)" 
"Firearm Fatalities Rate (Black)" "Firearm Fatalities Rate (Hispanic)" "Firearm Fatalities Rate (White)" "Non-Petitioned Cases" 
"Petitioned Cases" "Denominator" "Juvenile Arrest Rate" "Average Traffic Volume per Meter of Major Roadways" "# Homeowners" "% Homeowners" 
"# Households with Severe Cost Burden" "% Severe Housing Cost Burden" "# less than 18 years of age" "% less than 18 years of age" 
"pct_age65" "# Black" "% Black" "# American Indian & Alaska Native" "% American Indian & Alaska Native" "# Asian" "% Asian" 
"# Native Hawaiian/Other Pacific Islander" "% Native Hawaiian/Other Pacific Islander" "# Hispanic" "% Hispanic" "# Non-Hispanic White" 
"% Non-Hispanic White" "# Not Proficient in English" "% Not Proficient in English" "% Female" "# Rural" "% Rural" "positive" "negative" 
"pending" "hospitalizedCurrently" "hospitalizedCumulative" "inIcuCurrently" "inIcuCumulative" "onVentilatorCurrently" 
"onVentilatorCumulative" "recovered" "state_deaths" "hospitalized" "positiveTestsViral" "negativeTestsViral" "positiveCasesViral" 
"deathConfirmed" "deathProbable" "positiveIncrease" "negativeIncrease" "total" "totalTestResults" "totalTestResultsIncrease" "posNeg" 
"deathIncrease" "hospitalizedIncrease" "stay_at_home" "reopen" "reclosure" "mask" "date_since_social" "date_since_reopen" 
"date_since_reclosure" "date_since_mask" "beds" "date_since" "All.Cause.death_rate" "Assault.death_rate" "Cancer.death_rate" 
"Cardiovascular.death_rate" "Despair.death_rate" "PediatricAsthma" "AdultAsthma" "COPD" "AdultChronicLungDisease" "LungCancer" "cli" )

fname="NBGWAS.R"


for var in "${var_names[@]}"; do {
  echo `Rscript $fname var`&
} done
