library("MASS")
library("lme4")
library("glmmTMB")
library("gamm4")
library('caret')
library('blmeco')
library(pROC)
library(VineCopula)
library("PerformanceAnalytics")
library(glmmTMB)
library(ggplot2)
library(cvms)
library(sgof)
library(tidyverse)
library(kableExtra)


aggregate_pm_census_cdc_test_beds_age_diabete_obesity_heart<-readRDS('07-05-2020data-2.Rds')


combined.mode.nb.random.off.main = glmer.nb(Deaths ~ scale(hispanic) + scale(pct_blk) + scale(pct_asian) + scale(pct_white) + scale(pct_native)
                                            + factor(q_popdensity)
                                            + scale(log(medhouseholdincome))
                                            + scale(date_since_social) + scale(date_since) + scale(date_since_reopen)
                                            +scale(date_since_reclosure)+scale(date_since_mask)
                                            +scale(pct_obesity)
                                            +scale(pct_age65)+scale(pct_diabetes)
                                            +scale(LungCancer)
                                            +scale(COPD)
                                            +scale(AdultAsthma)
                                            +scale(PediatricAsthma)
                                            +scale(All.Cause.death_rate)
                                            + (1|state)
                                            + offset(log(population)), data = aggregate_pm_census_cdc_test_beds_age_diabete_obesity_heart)
combined.summary.July8<-summary(combined.mode.nb.random.off.main)
saveRDS(combined.summary.July8, file = 'combined.summary.July8')
