---
title: "ProtoNotebook"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "../")
```

```{r echo = F, results = 'hide',  warning=FALSE, message=FALSE}
#### Library and Data Imports ####
## Load essential R packages
source("Modules/Source.R")
## Load in model outputs per state:
source("Modules/load_model_output.R")
```

```{r echo = F, results = 'hide',  warning=FALSE, message=FALSE}
### P_value Table explanation
per_state_p_vals <- "<h4><b>Color-coordinate P-Value Summaries per parameter in the model per state?</b></h4>
Here, <span style='color:#c35442'><b>red</b></span> indicate non-significance (p > 0.10)<br><br> 
<span style='color:#d58570'><b>light red</b></span> indicate significance (0.05 < p < 0.10)<br><br> 
<span style='color:#d4e6e8'><b>light blue</b></span> indicate significance (0.01 < p < 0.05)<br><br> 
<span style='color:#94c0c6'><b>blue</b></span> indicate significance (p < 0.01)<br><br>"

```

  `r per_state_p_vals`

```{r echo = F}


  color_format <- function(x, na.rm = TRUE) {
  
  ifelse(x >0.10,
         cell_spec(x, "html", color = "#000000", background = "#c35442"),  # RED (over .1)
         ifelse(x>0.05,
                cell_spec(x, "html", background ="#d58570", color = "#000000"),  # (over .05)
                ifelse(x>0.01,
                       cell_spec(x, "html", background ="#d4e6e8", color = "#000000"), # (over .01)
                       cell_spec(x, "html", background ="#94c0c6", color = "#000000")))) # (under .01)
  
  }
  rounder <- function(x, na.rm = TRUE) {
    round(x, digits = 3)
  }
  
  t2 <- as_tibble(states.all_p)
  
  t2 %>%
  mutate_if(is.double, rounder, na.rm = TRUE) %>%
  mutate_if(is.double, color_format, na.rm = TRUE) %>%
  kable(format = "html", escape = F, row.names = TRUE) %>%
  kable_styling(full_width = T) 
  
  t2
```




```{r echo = F}




```

