---
title: "Deltas in cases/NY"
author: "Jose Figueroa"
date: 05/14/2020
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "../")
```

```{r echo = F, results = 'hide',  warning=FALSE, message=FALSE}
#### Library and Data Imports ####

## Load essential R packages
source("modules/Source.R")

## Load stored data (see `data` subdirectory)
source("modules/data_load.R")

## Create dataframes; perform desparity index calcuations; prep for plotting
source("modules/preprocessing.R")
```

Dataset will be primarily covid_NY_TS_plot.cases

```{r}
covid_NY_TS_plot.cases %>% glimpse()
```

```{r}
covid_NY_TS_plot.cases %>% summary()
```

```{r}

    NY_region_palette.df <- NY_counties_regions %>%
      dplyr::select(Region,Color) %>% 
      dplyr::distinct(Region,Color)
    
    NY_region_palette <- setNames(as.character(NY_region_palette.df$Color), as.character(NY_region_palette.df$Region))

    
covid_NY_TS_plot.cases %>%
  filter(!County %in% c("New York",
                        "New York State")) %>%
  ggplot(
    aes(
      x = date,
      y = diff,
      color = Region,
      group = County
    )
  ) +
  scale_color_manual(values=NY_region_palette) +
  geom_line(size = 1) + 
        scale_y_continuous(
        breaks = c(-200,5,10,100,1000,2500,5000,7500,10000)
      ) +
      scale_x_datetime(date_breaks = "1 week", date_minor_breaks = "1 day", date_labels = "%b %d") +
    NULL
```

```{r}
covid_NY_TS_plot.cases %>%
  ggplot(
    aes(
      x = date,
      y = p_diff,
      color = Region,
      group = County
    )
  ) +
  geom_line(size = 1) +       scale_y_continuous(
        breaks = c(-200,10,50,100,150,200,250, 300, 500)
      ) +
      scale_x_datetime(date_breaks = "1 week", date_minor_breaks = "1 day", date_labels = "%b %d") +
    NULL
```

Interesting discrepencies...

```{r}
NY_region_palette.df <- NY_counties_regions %>%
dplyr::select(Region,Color) %>% 
dplyr::distinct(Region,Color)

NY_region_palette <- setNames(as.character(NY_region_palette.df$Color), as.character(NY_region_palette.df$Region))

covid_NY_TS_plot.cases %>%
  group_by(Region, date) %>%
  summarise(diff = sum(diff)) %>%
  mutate(ma = c(NA, NA,rollmean(diff, 3, align = "right"))) %>%
      ggplot(aes(date, 
                 ma, 
                 color = Region)) +
      scale_color_manual(values=NY_region_palette) +
      geom_line(size = 1) +
      scale_y_continuous(
        trans = "log10",
        breaks = c(10,100,500,1000,5000,10000, 50000)
      ) +
      scale_x_datetime(date_breaks = "1 week", date_minor_breaks = "1 day", date_labels = "%b %d") +
      ylab("New Cases") + 
      xlab("Date") +
      ggtitle("New York State NEW reported COVID-19 Cases") +
      geom_vline(aes(xintercept=as_datetime("2020-03-20"), linetype="Gov. Cuomo issues stay-at-home order"), color = "black") + 
      scale_linetype_manual(name = "Events", 
                            values = c(2), 
                            guide = guide_legend(override.aes = list(color = c("black")))) +
      NULL
```

```{r}
# rollmean from zoo::rollmean

NY_region_palette.df <- NY_counties_regions %>%
dplyr::select(Region,Color) %>% 
dplyr::distinct(Region,Color)

NY_region_palette <- setNames(as.character(NY_region_palette.df$Color), as.character(NY_region_palette.df$Region))

covid_NY_TS_plot.cases %>%
  group_by(Region, date) %>%
  summarise(p_diff = sum(p_diff)) %>%
  mutate(ma = c(NA, NA,rollmean(p_diff, 3, align = "right"))) %>%
      ggplot(aes(date, 
                 ma, 
                 color = Region)) +
      scale_color_manual(values=NY_region_palette) +
      geom_line(size = 1) +
      scale_y_continuous(
        trans = "log10",
        breaks = c(10,100,500,1000,5000,10000,50000)
      ) +
      scale_x_datetime(date_breaks = "1 week", date_minor_breaks = "1 day", date_labels = "%b %d") +
      ylab("New cases per 100k") + 
      xlab("Date") +
      ggtitle("New York State NEW COVID-19 cases per 100k") +
      geom_vline(aes(xintercept=as_datetime("2020-03-20"), linetype="Gov. Cuomo issues stay-at-home order"), color = "black") + 
      scale_linetype_manual(name = "Events", 
                            values = c(2), 
                            guide = guide_legend(override.aes = list(color = c("black")))) +
      NULL
```

```{r}
NY_region_palette.df <- NY_counties_regions %>%
dplyr::select(Region,Color) %>% 
dplyr::distinct(Region,Color)

NY_region_palette <- setNames(as.character(NY_region_palette.df$Color), as.character(NY_region_palette.df$Region))

covid_NY_TS_plot.cases %>%
  group_by(County) %>%
  mutate(p_diff = max(0, p_diff)) %>%
  mutate(ma = c(NA, NA,rollmean(p_diff, 3, align = "right"))) %>%
      ggplot(aes(date, 
                 ma, 
                 color = Region)) +
      scale_color_manual(values=NY_region_palette) +
      geom_line(size = 1) +
      scale_y_continuous(
        trans = "log10",
        breaks = c(10,100,500,1000,5000,10000, 50000)
      ) +
      scale_x_datetime(date_breaks = "1 week", date_minor_breaks = "1 day", date_labels = "%b %d") +
      ylab("New cases per 100k") + 
      ggtitle("Rate of new COVID cases per 100k") +
      geom_vline(aes(xintercept=as_datetime("2020-03-20"), linetype="Gov. Cuomo issues stay-at-home order"), color = "black") + 
      scale_linetype_manual(name = "Events", 
                            values = c(2), 
                            guide = guide_legend(override.aes = list(color = c("black")))) +
      NULL
```

